"""CTA URL placeholder injection — seamless UTM link weaving for post content.

WHY THIS EXISTS
---------------
Each piece's UTM links live in ``utm_links.json`` (generated by
``jobs.utm_generator``), but historically schedule_planner only used
those for the ``utm_*`` columns in publishings — the actual content
sent to Postiz never embedded the click URL. Result: YT video
descriptions and LinkedIn posts went live with no clickable UTM link →
0 attribution.

The fix is "**seamless placeholder injection**": every platform's
draft markdown (and the LLM-derived YouTube description) writes a
``{{CTA_URL}}`` placeholder in the CTA sentence — the author writes the
copy that wraps the URL, the engine fills the URL in at publish time.
This keeps the CTA voice author-controlled and the URL machine-
generated.

USAGE
-----

   content = "你做的是 Schwab 卖得了的还是卖不了的? 测一下 -> {{CTA_URL}}"
   output  = inject_cta(content, "https://taskon.xyz/...?utm_source=youtube&...")
   # -> "你做的是 Schwab 卖得了的还是卖不了的? 测一下 -> https://taskon.xyz/..."

Fallback behavior (``strict=False``, the default):
   If ``{{CTA_URL}}`` is not present, the URL is appended on its own
   line at the end of the content with a WARN log so authors notice
   and edit the markdown for the next piece. ``strict=True`` raises
   instead — useful for the YT description path where we know the LLM
   was instructed to embed the placeholder.

PLACEHOLDER CONVENTION
----------------------
Curly-brace double-bracket is conventional in Jinja-adjacent
ecosystems; here we use the literal string ``{{CTA_URL}}`` (no Jinja
runtime). This is the only placeholder this module knows about — keep
the surface narrow on purpose.
"""
from __future__ import annotations

import logging
import re


logger = logging.getLogger(__name__)


PLACEHOLDER = "{{CTA_URL}}"
PLACEHOLDER_RE = re.compile(re.escape(PLACEHOLDER))


class MissingPlaceholderError(RuntimeError):
    """Raised in strict mode when content has no ``{{CTA_URL}}`` placeholder."""


def has_placeholder(content: str) -> bool:
    """Whether ``content`` contains at least one ``{{CTA_URL}}`` token."""
    return PLACEHOLDER in content


def count_placeholder(content: str) -> int:
    """Number of ``{{CTA_URL}}`` occurrences. Authors may want only 1 — caller
    can decide what to do if multiple appear."""
    return len(PLACEHOLDER_RE.findall(content))


def inject_cta(content: str, cta_url: str, *, strict: bool = False) -> str:
    """Replace every ``{{CTA_URL}}`` placeholder in ``content`` with ``cta_url``.

    Args:
        content: The platform draft text (markdown / plain) or yt
            description.
        cta_url: Full URL to substitute (long URL with UTM params; see
            ``utm_links.json``).
        strict: When True, raise :class:`MissingPlaceholderError` if no
            placeholder is found. When False (default), append the URL
            to the end and emit a WARN log so authors notice.

    Returns:
        The content with placeholder replaced.

    Raises:
        ValueError: If ``cta_url`` is empty or doesn't start with
            http(s)://.
        MissingPlaceholderError: strict=True and no placeholder present.
    """
    if not cta_url or not isinstance(cta_url, str):
        raise ValueError(f"cta_url must be non-empty string, got {cta_url!r}")
    if not cta_url.startswith(("http://", "https://")):
        raise ValueError(f"cta_url must start with http(s)://, got {cta_url[:60]!r}")

    if not has_placeholder(content):
        if strict:
            raise MissingPlaceholderError(
                f"content has no {PLACEHOLDER} placeholder — author must "
                f"add it where the CTA link should appear"
            )
        logger.warning(
            "inject_cta fallback: no %s placeholder found — appending CTA URL "
            "to end of content. Author should edit the markdown for next time.",
            PLACEHOLDER,
        )
        # Append on its own line with a blank separator so it doesn't run on
        # to the prior paragraph; keep the rest of the content as-is to avoid
        # whitespace surprises.
        return content.rstrip() + "\n\n" + cta_url + "\n"

    n = count_placeholder(content)
    if n > 1:
        # Multiple placeholders in one piece is suspicious (CTA should
        # typically appear once). Log and replace all anyway — author
        # might be A/B testing.
        logger.warning(
            "inject_cta: content has %d %s placeholders (typical = 1); "
            "replacing all",
            n, PLACEHOLDER,
        )
    return PLACEHOLDER_RE.sub(cta_url, content)


__all__ = [
    "PLACEHOLDER",
    "MissingPlaceholderError",
    "has_placeholder",
    "count_placeholder",
    "inject_cta",
]
